// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXC3hMXVhPVWlYM5z_wX2a3b-tCg7jjfs',
    appId: '1:457287100758:android:cb96449638f5000a028ef7',
    messagingSenderId: '457287100758',
    projectId: 'techxpark-67c25',
    databaseURL: 'https://techxpark-67c25-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'techxpark-67c25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzidstWOerTu2owYuYs8uiO5NRUrvVdxc',
    appId: '1:457287100758:ios:0339dd318207d1e6028ef7',
    messagingSenderId: '457287100758',
    projectId: 'techxpark-67c25',
    databaseURL: 'https://techxpark-67c25-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'techxpark-67c25.firebasestorage.app',
    androidClientId: '457287100758-023eia10ogm5mbqr9acmvac9tfqc6og5.apps.googleusercontent.com',
    iosClientId: '457287100758-13o6nc7ua6ejkir0rbvv2strp471c5ns.apps.googleusercontent.com',
    iosBundleId: 'com.techxpark.parking',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIzofvIykqBqdadR66B7vE2Tmsn32KLpE',
    appId: '1:457287100758:web:d6ccaa715cee7ea8028ef7',
    messagingSenderId: '457287100758',
    projectId: 'techxpark-67c25',
    authDomain: 'techxpark-67c25.firebaseapp.com',
    databaseURL: 'https://techxpark-67c25-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'techxpark-67c25.firebasestorage.app',
    measurementId: 'G-QFYGM34ZL9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIzofvIykqBqdadR66B7vE2Tmsn32KLpE',
    appId: '1:457287100758:web:b4acb5941ba03fa9028ef7',
    messagingSenderId: '457287100758',
    projectId: 'techxpark-67c25',
    authDomain: 'techxpark-67c25.firebaseapp.com',
    databaseURL: 'https://techxpark-67c25-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'techxpark-67c25.firebasestorage.app',
    measurementId: 'G-MNQ6B5F2W2',
  );

}
